### ISSUE TITLE
NullPointerException when requesting the service identification with the default locale

### ISSUE THREAD

**Issue by autermann** [52North/arctic-sea#112]
2cf75e41fa5dcb26922f1fd446a2e91e0bb6a1a5 introduced a bug the results in a `NullPointerException` when `OwsServiceIdentificationFactory.create()` is called. The producer will pass a `locale` down to the factory which doesn't check for `null` in the [`getTitle(Locale)`](https://github.com/52North/arctic-sea/blob/v7.3.0/iceland/core/src/main/java/org/n52/iceland/ogc/ows/OwsServiceIdentificationFactory.java#L182) and [`getAbstract(Locale)`](https://github.com/52North/arctic-sea/blob/v7.3.0/iceland/core/src/main/java/org/n52/iceland/ogc/ows/OwsServiceIdentificationFactory.java#L198) methods.

**Comment by matthesrieke** [comment]
@autermann the 7.3.1 release does not solve the issue in the eopad backend. I am still getting:

```
java.lang.NullPointerException
	at org.n52.janmayen.i18n.LocaleHelper.getEquivalents(LocaleHelper.java:73)
	at org.n52.iceland.ogc.ows.OwsServiceIdentificationFactory.getTitle(OwsServiceIdentificationFactory.java:200)
	at org.n52.iceland.ogc.ows.OwsServiceIdentificationFactory.createFromSettings(OwsServiceIdentificationFactory.java:157)
	at org.n52.iceland.ogc.ows.OwsServiceIdentificationFactory.create(OwsServiceIdentificationFactory.java:145)
	at org.n52.iceland.ogc.ows.OwsServiceIdentificationFactory.create(OwsServiceIdentificationFactory.java:46)
	at org.n52.iceland.util.LocalizedLazyThreadSafeProducer.create(LocalizedLazyThreadSafeProducer.java:66)
	at org.n52.iceland.util.LazyThreadSafeProducer.get(LazyThreadSafeProducer.java:65)

```

The problem lies imho at https://github.com/52North/arctic-sea/blob/master/iceland/core/src/main/java/org/n52/iceland/util/LocalizedLazyThreadSafeProducer.java#L66, using explicitly `null` as the constructor arg.

**Comment by autermann** [comment]
Nope. The stacktrace has definitely been produced by arctic sea `<=7.3.0`

**Comment by matthesrieke** [comment]
yap, was an issue with muliple versions due to the WAR overlay structure of the project..
