### ISSUE TITLE
IPv6 of the IPv4 address format exception

### ISSUE THREAD

**Issue by autermann** [52North/arctic-sea#14]
I'd like to make a query against the new SOS 5.x deployment and in the logs the following message appears.

`2015-07-06 07:32:18,193 WARN [http-nio-127.0.0.1-8080-exec-31] [ProxyChain.java:133] Ignoring invalid IP address in X-Forwared-For header: ::ffff:217.173.34.182
java.lang.IllegalArgumentException: '' is not an IP string literal.
    at com.google.common.net.InetAddresses.forString(InetAddresses.java:153) ~[InetAddresses.class:na]
    at org.n52.iceland.util.net.IPAddress.parse(IPAddress.java:125) ~[IPAddress.class:na]
    at org.n52.iceland.util.net.IPAddress.<init>(IPAddress.java:59) ~[IPAddress.class:na]
    at org.n52.iceland.util.net.ProxyChain.getIPAddress(ProxyChain.java:141) ~[ProxyChain.class:na]
    at org.n52.iceland.util.net.ProxyChain.fromForwardedForHeader(ProxyChain.java:128)`

full stacktrace: https://gist.github.com/lestarcdog/897d32d8198b29622e79

See https://github.com/52North/iceland/issues/20.

**Comment by autermann** [comment]
Implemented in 7d2f982a36fd5442dd46a308826ef88c3096ad2a.
