### ISSUE TITLE
java.lang.ClassNotFoundException: org.n52.svalbard.encode.TestAbstractSensorMLEncoder

### ISSUE THREAD

**Issue by EHJ-52n** [52North/arctic-sea#27]
I am using the latest release and the [`svalbard-xmlbeans-context.xml`](https://github.com/52North/arctic-sea/blob/381a88d20fd9064e4d997e28943bb2495050a447/svalbard/xmlbeans/src/main/resources/svalbard-xmlbeans-context.xml#L180) contains a bean definition for an abstract class:
```
cnc_1         | Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.n52.svalbard.encode.TestAbstractSensorMLEncoder] for bean with name 'org.n52.svalbard.encode.TestAbstractSensorMLEncoder#0' defined in URL [jar:file:/tmp/service.jar!/BOOT-INF/lib/core-0.0.1-SNAPSHOT.jar!/svalbard-xmlbeans-context.xml]; nested exception is java.lang.ClassNotFoundException: org.n52.svalbard.encode.TestAbstractSensorMLEncoder
cnc_1         |         at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1380) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:670) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:637) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1489) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:420) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:390) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:222) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1276) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         ... 26 common frames omitted
cnc_1         | Caused by: java.lang.ClassNotFoundException: org.n52.svalbard.encode.TestAbstractSensorMLEncoder
cnc_1         |         at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_151]
cnc_1         |         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_151]
cnc_1         |         at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[service.jar:0.0.1-SNAPSHOT]
cnc_1         |         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_151]
cnc_1         |         at org.springframework.util.ClassUtils.forName(ClassUtils.java:264) ~[spring-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:437) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1428) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1372) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
cnc_1         |         ... 37 common frames omitted
```

@autermann could you please fix this and create 5.0.1, too?

**Comment by EHJ-52n** [comment]
@CarstenHollmann fixed this in dd70fe9642df54f25e.
